# Use postgres/example user/password credentials
version: '3.8'

volumes:
  database-storage:

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - database-storage:/var/lib/postgresql/data/
    env_file: .env
    ports:
      - 5432:5432
    
   
  # studio:
  #   image: calcom.docker.scarf.sh/calcom/cal.com
  #   restart: always
  #   ports:
  #     - 5555:5555
  #   env_file: .env
  #   environment:
  #     - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DATABASE_HOST}/${POSTGRES_DB}
  #   depends_on:
  #     - database
  #   command:
  #     - npx
  #     - prisma
  #     - studio
# END SECTION: Optional use of Prisma Studio.
